import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Configura a fonte Geist Sans para ser usada globalmente via CSS custom property.
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

// Configura a fonte Geist Mono para ser usada globalmente via CSS custom property.
const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// Metadados da aplicação que o Next.js usa para preencher tags <title> e meta.
export const metadata: Metadata = {
    title: "The Social Blog - Livia Livela",
    description: "Generated by create next app",
};

// Componente de layout raiz que envolve todas as páginas do app.
// O `children` representa o conteúdo específico de cada página renderizada.
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="pt-br">
            <body>{children}</body>
        </html>
    );
}
